runtime: nodejs20

instance_class: F1  # Small, free tier eligible

entrypoint: node server.js

env_variables:
  NODE_ENV: "production"



automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1  # Set to 0 for cost saving (cold starts possible)
  max_instances: 3


handlers:
  # Serve static files with appropriate cache settings
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  # All other requests get routed to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache"