// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcgaqikuaaazjpwyzvwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZ2FxaWt1YWFhempwd3l6dndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTk2MDMsImV4cCI6MjA2NDY5NTYwM30.7X3B8iJF349EyapcVogsvgomKFgxinmRS2q8lk72hGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);